#don't need to mentions links option
#because containers communicate with bridge network
#add version at top file

version: "2"

services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end
    restart: always
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - front-end
      - back-end


  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - front-end
      - back-end

  worker:
    image: bretfisher/examplevotingapp_worker:java
    depends_on:
      - db
      - redis
    networks:
      - back-end

networks:
  front-end:
  back-end:

