 version: '2'

 services:
   drupal:
    image: drupal
    ports:
     - 8080:80
    volumes:
     - drupal-modules:/var/www/html/modules
     - drupal-profiles:/var/www/html/profiles
     - drupal-sites:/var/www/html/sites
     - drupal-themes:/var/www/html/themes
    networks:
     - mybridge
   postgres:
    image: postgres
    networks:
     - mybridge
    volumes:
     - psql-date:/var/lib/postgresql/data
    environment:
     POSTGRES_PASSWORD: 123qwe
     POSTGRES_USER: postgres
 volumes:
   drupal-modules:
   drupal-profiles:
   drupal-sites:
   drupal-themes:
   psql-date:
 networks:
   mybridge:
                                                                                                                                 

